### ISSUE TITLE
Issues & TODOs Ver. 1.0

### ISSUE THREAD

**Issue by tolaoyelola** [charlesinto/nexportrade#1]
@charlesinto

`Well done so far. As usual we are not judging your work but we are also aware that no one is perfect, so in your quest to perfection, here's a little guide to smoothen your journey😉:`

___
> :warning: _Alert!_ 
_Some links and sections are very likely to be absent in the final product: The current version is simply to help the client understand our vision and their progress!_
___

### **OBSERVATIONS & NOTES**

1. The local build seems different aesthetically to the online version.
2. I like the positioning and sizing on the local build. It looks more aesthetically pleasing.
3. We need a terms & policy page

___
### INTERFACE

1. Dead/Wrong/Inactive Links:
- [ ] _Learn More_ - Buttons - On the homepage - for each service - should lead to the individual service's page.
- [ ] _CTA 2_ - Links - On the homepage - for each service - should lead to the contact page.
- [ ] _Learn More_ - Button - On the homepage - for the coming soon CTA to the Virtual showroom page - should lead to the virtual showroom page.
- [x] _Meet The Team_ - Link - On the footer - should link to the Our Team page.
- [x] Leadership History - Link - On the footer - should link to the Leadership History.
- [x] _Learn More_ - Buttons - On the services page - for each service - should lead to the service's page.
- [ ] _Learn More_ - Button - On the services page - for the coming soon CTA to the Virtual showroom page - should lead to the virtual showroom page.
- [x] _About us_ - Link - On the services page - for the vision CTA - should link to the about us page.

2. The dropdown on the contact form has no options.
4. There is no form action on the contact form. When will we implement mailgun to receive messages from the contact form?
5. The above situation is similar for the newsletter subscription form.
6. The map on the contact us page seems non-functional and doesn't highlight the Nexportrade office address - do you need a google maps api key?

___
### STYLING
- [ ] Use the full color style logo on the menu and NOT the plain monochrome version
- [ ] Reduce the font size on the menu a smidge, and perhaps bolden the text too.
- [ ] Align the left side of the hero text on the homepage with the logo in the menu. You will notice the pleasing symmetry after you do this.
- [ ] Position the images to give a more appealing crop.
- [x] Learn more links on the services page have been chopped off at the tip. Is this some weird sexual reference? 🙈🤔
![image](https://user-images.githubusercontent.com/22857325/166507880-d2494f8e-deec-4603-8064-1e214a8eaba2.png)
- [ ] Reduce the icon size on the contact options for the contact us page.
- [ ] Reduce the font size for the contact form on the contact us page by a little - perhaps 1 unit.
- [ ] The links, T's & C's as well as the subscription form on the footer need

___
### CONTENT

- [ ] Change the name of the "Contacts" page to "Contact Us or Contact"

- [ ] The Virtual showroom page seems to be missing.
- [ ] The logo for Manufacturers Association of Nigeria is missing in the partners CTA on all pages.
- [ ] The logos should have a hover effect that turn them to a colored variant - otherwise just use the colored version of the partner logos - and onClick, the logos should lead to each partner's website.
- [ ] The Activities and biography pages/popups are missing for the leadership history page.
- [ ] There is no feedback on the job openings page _e.g. no jobs available currently_.
- [ ] The CTA for leadership history & meet the team on the job openings page is wrong.

___
### ISSUES WITH RESPONSIVE DESIGN
- [x] Add the hero image to the homepage.
- [x] The line break on the warehousing solutions section of the homepage doesn't look good - For the subheading reading: _As a temporary hold for tradeshows._
- [x] The CTAs look a bit squeezed - perhaps some more breathing room:
![image](https://user-images.githubusercontent.com/22857325/166507671-8c7fa92c-d623-46f3-b4e0-1b7546a41de3.png)
- [ ] There are no footer links in the mobile view. Is this by design?
- [ ] The address - with the darker shade - should be in the middle row of the business's contact on the footer

### TODO FOR TOLA

- ~~Update the contact us dropdown~~
- Update the virtual showroom content
- Contact us still has a lorem ipsum on it
- Design the footer links
